spring.application.name=Penguin List API
spring.datasource.url=jdbc:sqlite:penguin-list.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.hikari.connection-init-sql=PRAGMA foreign_keys=ON
spring.sql.init.mode=always
